baseURL = 'https://idralliance.global'
languageCode = 'en-us'
disableHugoGeneratorInject = true
title = 'IDRA — International Drought Reslience Alliance'

[params]
copyright = "Copyright © 2022-2023 IDRA / UNCCD"
metaDescription = "International Drought Resilience Alliance (IDRA) - The global alliance for drought resilience and preparedness"
metaImage = "/images/og-image.png"
